version: '3'

services:

  spring-boot-redis-todo-app:
    build: .
    ports:
      - 80:80
    volumes:
      - ~/java/springboot/springboot-redis-todo-app:/usr/src/app
    networks:
      - spring-boot-redis-todo-app-network
    depends_on:
      - redis

  redis:
    image: redis:latest
    hostname: redis
    volumes:
      - ~/java/db/redis:/data
    ports:
      - 6387:6379
    networks:
          - spring-boot-redis-todo-app-network

networks:
  spring-boot-redis-todo-app-network: